name: mi_app_futsal
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev, using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# In Windows, build-name is used as product and file versions while build-number is used as numeric part
# of product and file versions.
version: 1.0.0+1

# CORRECCIÓN AQUÍ: Asegúrate de que 'environment:' esté correctamente indentado
# y que 'sdk:' esté indentado debajo de 'environment:'.
environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  uuid: ^4.4.0 # Para generar IDs únicos
  provider: ^6.0.5 # Para la gestión de estado
  csv: ^5.1.1 # Para exportar datos a CSV
  url_launcher: ^6.2.2 # Para abrir URLs (útil para descargar CSV en web)
  fl_chart: ^0.68.0 # Para gráficos
  excel: ^2.0.0
  path_provider: ^2.0.15
  share_plus: ^6.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Material Icons class.
  uses-material-design: true
